### ISSUE TITLE
Computer Vision

### ISSUE THREAD

**Issue by chlohal** [nhs-t10/Robotics_2021_2022#1]
Identify which spot the duck is on with a webcam.

**Comment by coleh2** [comment]
Installed successfully; now, we need to write a pipeline to identify the actual thing. We can base it off of the examples that arnon found: https://github.com/OpenFTC/EasyOpenCV/tree/0f571483025be99bb4df4b75b0530a0a32be24ea/examples/src/main/java/org/openftc/easyopencv/examples
