### ISSUE TITLE
Re-write or delete SensorManager

### ISSUE THREAD

**Issue by chlohal** [nhs-t10/Robotics_2021_2022#25]
Whether you re-write or delete is up to whoever takes this issue. Either solution is equally justified-- deleting it cleans up our codebase, and re-writing gives more utility to future years.

### If you Decide to Re-Write

- [x] Move the `ColorSensor` helper class from the `auxilliary` package into the `managers/sensor` package
- [x] Move the general `Sensor` super-class from  `auxilliary` to `managers/sensor`.
- [x] Make the general Sensor super-class have a few methods-- `isSpecial()` especially!
- [x] Brainstorm -- what are some things that *all* sensors have in common? ("getNumberValue()", "getFloatArray()", etc. don't be afraid to stretch it; we already have `isSpecial()`) Add them to `Sensor` as [abstract methods](https://docs.oracle.com/javase/tutorial/java/IandI/abstract.html).
- [x] Add a quick implementation of the general common methods to `ColorSensor`
- [x] **Add javadoc comments in `SensorManager`! (`/**`)**

**Comment by Mario-Runner** [comment]
Rewrote the issue to only contain the rewrite tasks, as I chose to rewrite SensorManager instead of deleting it.

**Comment by Mario-Runner** [comment]
All tasks involving the rewrite are complete, SensorManager now differentiates between colorSensors, touchSensors, and distanceSensors similarly to ManipulationManager's differentiation between DCMotors, Servos, and CRServos.
