### ISSUE TITLE
Beautify the glue code

### ISSUE THREAD

**Issue by chlohal** [nhs-t10/Robotics_2021_2022#27]
Right now, 90% of ExampleTeleopCarouselDualController's `loop()` method is "glue code"/"middleware". It takes a value from the InputManager and calls a method in one of the others.

### Can we automate this?

I don't have any implementation ideas for *how* we'd do it, but it'd be cool if all of that could be simplified-- like the `PriorityAsyncOpmodeComponent` does-- and made understandable.

#### Challenges

- Some nodes rely on each other (like `ClawDown` having to check `ClawUp`)
- The `else` statements-- code needs to be ran when nodes *aren't* true
- Current code relies on being in the same loop (e.g. the toggle dashing bit)

#### Implementation Ideas

Okay, I lied. I have a few.

- Some kind of "constraint" system to fix challenge 1. Something like
  ```java
  input.registerConstraint( new OneOfConstraint("ClawDown", "ClawUp"));
  ```
  would make it so *only* one of `ClawDown`/`ClawUp` would be activated at a time. This would solve the issue of having to check them, but I have no *idea* how we'd do it.

**Comment by chlohal** [comment]
Challenge 2-- we could put the `if`/`else` inside the proposed lambda. Baby steps! It's not all going to be pure nodes :)

**Comment by chlohal** [comment]
Obviously, if we *do* do this, it would need the cooperation of *everyone*, and it won't be done soon. We can think about doing it after our competitions.

**Comment by chlohal** [comment]
Having some ideas about this; started work on the [`entirely-nodes-teleop`](/nhs-t10/Robotics_2021_2022/tree/entirely-nodes-teleop) branch

**Comment by Mario-Runner** [comment]
I've optimized Teleop in DualControllerFools quite significantly to primarily use nodes instead of large numbers of if statements in loop.
