### ISSUE TITLE
[low-priority] [autoauto] Fix compiling after a gitignore

### ISSUE THREAD

**Issue by chlohal** [nhs-t10/Robotics_2021_2022#4]
When the compiler checks for robot functions (`autoauto/compiler/functionloader/index.js`), it should check if the `robotfunctions` directory exists. If it doesn't, the **cache file should automatically be deleted**.

This fixes a problem where the compiler assumes deleted files still exist since the cache hasn't changed.

For whoever does this, make sure to do it *before* line 14, since that's what loads the cache file.

**Comment by coleh2** [comment]
For now, we can work around this by manually deleting the `autoauto/compiler/functionloader/.cache` directory
