### ISSUE TITLE
Make the PIDlessEncoderMovementThread self-correcting

### ISSUE THREAD

**Issue by chlohal** [nhs-t10/Robotics_2021_2022#47]
### Current State:
We have a hard-coded `-1 *` on line 40 of `PIDlessEncoderMovementThread.java` to account for weirdness in the directions. We don't know where the weirdness came from.

### Ideal:
The `PIDlessEncoderMovementThread` should be able to adapt to any direction. We *can* see the motor ticks accurately, so why don't we:
- [x] Keep track of the way it's changing
- [x] If the change is taking us away from the target value, multiply the next changes by `-1`

With the x-axis being time, here's an an explanation of how it might work. In the purple region, we're giving a *positive* change, but getting a negative output. 
![diagram of explanation](https://user-images.githubusercontent.com/26300854/150643031-d5b14e88-448d-42d0-bc45-1f3b050c415f.png)

Ideally, this will make it *super* easy in the future: the motors can run whichever way they want, and as long as they report accurate ticks, `PIDlessEncoderMovementThread` will just adapt to them!

### Why Not Just Have The -1?
It works *now*, but if someone plugs in a motor incorrectly, we have to hunt down the issue and fix it again. That's wasted time that we could spend on something else!

**Comment by chlohal** [comment]
> We don't know where the weirdness came from.
Not... entirely accurate-- I have a suspicion, at least, that it's from DcMotors being plugged in backwards, which inverts their directions

**Comment by Arnon-K** [comment]
Robot still Works; need to test by switching motor around!!!

**Comment by Arnon-K** [comment]
Robot still Works; need to test by switching motor around!!!
